//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kinoteatr
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Film()
        {
            this.Seans = new HashSet<Seans>();
        }
    
        public int ID_Film { get; set; }
        public string NameFilm { get; set; }
        public byte[] Photo { get; set; }
        public string PhotoURL { get; set; }
        public string Zanr { get; set; }
        public string Ogranichenie { get; set; }
        public string Opisanie { get; set; }
        public Nullable<System.DateTime> Date_seans { get; set; }
        public Nullable<System.TimeSpan> time_seans { get; set; }
        public Nullable<System.TimeSpan> Time_Film { get; set; }
        public string Country { get; set; }
        public string Zal { get; set; }
        public string mesto1 { get; set; }
        public string mesto2 { get; set; }
        public string mesto3 { get; set; }
        public string mesto4 { get; set; }
        public string mesto5 { get; set; }
        public string mesto6 { get; set; }
        public string mesto7 { get; set; }
        public string mesto8 { get; set; }
        public string mesto9 { get; set; }
        public string mesto10 { get; set; }
        public string mesto11 { get; set; }
        public string mesto12 { get; set; }
        public string mesto13 { get; set; }
        public string mesto14 { get; set; }
        public string mesto15 { get; set; }
        public string mesto16 { get; set; }
        public string mesto17 { get; set; }
        public string mesto18 { get; set; }
        public string mesto19 { get; set; }
        public string mesto20 { get; set; }
        public string mesto21 { get; set; }
        public string mesto22 { get; set; }
        public string mesto23 { get; set; }
        public string mesto24 { get; set; }
        public string mesto25 { get; set; }
        public string mesto26 { get; set; }
        public string mesto27 { get; set; }
        public string mesto28 { get; set; }
        public string mesto29 { get; set; }
        public string mesto30 { get; set; }
        public string Zal2mesto1 { get; set; }
        public string Zal2mesto2 { get; set; }
        public string Zal2mesto3 { get; set; }
        public string Zal2mesto4 { get; set; }
        public string Zal2mesto5 { get; set; }
        public string Zal2mesto6 { get; set; }
        public string Zal2mesto7 { get; set; }
        public string Zal2mesto8 { get; set; }
        public string Zal2mesto9 { get; set; }
        public string Zal2mesto10 { get; set; }
        public string Zal2mesto11 { get; set; }
        public string Zal2mesto12 { get; set; }
        public string Zal2mesto13 { get; set; }
        public string Zal2mesto14 { get; set; }
        public string Zal2mesto15 { get; set; }
        public string Zal2mesto16 { get; set; }
        public string Zal2mesto17 { get; set; }
        public string Zal2mesto18 { get; set; }
        public string Zal2mesto19 { get; set; }
        public string Zal2mesto20 { get; set; }
        public string Zal2mesto21 { get; set; }
        public string Zal2mesto22 { get; set; }
        public string Zal2mesto23 { get; set; }
        public string Zal2mesto24 { get; set; }
        public string Zal2mesto25 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seans> Seans { get; set; }
    }
}
