//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kinoteatr
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class user12_dbEntities : DbContext
    {
        public user12_dbEntities()
            : base("name=user12_dbEntities")
        {
        }

        private static user12_dbEntities _context;

        public static user12_dbEntities GetContext()
        {
            if (_context == null)
                _context = new user12_dbEntities();

            return _context;

        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Film> Film { get; set; }
        public virtual DbSet<Seans> Seans { get; set; }
        public virtual DbSet<User1> User1 { get; set; }
    }
}
