//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kinoteatr
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seans
    {
        public int ID_Seans { get; set; }
        public Nullable<int> IDFilm { get; set; }
        public System.DateTime DataSeans { get; set; }
        public string time { get; set; }
        public string Mesta { get; set; }
    
        public virtual Film Film { get; set; }
    }
}
