//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kinoteatr
{
    using System;
    using System.Collections.Generic;
    
    public partial class User1
    {
        public int ID_User { get; set; }
        public string loginUser { get; set; }
        public string passUser { get; set; }
        public string Fama { get; set; }
        public string Name { get; set; }
        public string Otch { get; set; }
        public string EmailUser { get; set; }
        public string phoneUser { get; set; }
    }
}
